### ISSUE TITLE
Bug or version issue in json_serializers.py?

### ISSUE THREAD

**Issue by eblur** [gregreen/dustmaps#11]
When I try to run `BayestarWebQuery`, I get a type error that seems connected to the `astropy.coordinates.SkyCoord` object. But it traces back to dustmaps/json_serializers.py

* Running Python 3.6, Astropy 3.0.2
* Error reproduced on two computers
* Works in Python 2.7, Astropy 2.0.6

```
import astropy.units as u
from astropy.coordinates import SkyCoord
from dustmaps.bayestar import BayestarWebQuery
DIST = np.arange(0.1, 2.501, 0.1) * u.kpc
V404 = SkyCoord(ra='20h24m03.820s', dec='+33d52m01.90s', distance=DIST)
bayestar = BayestarWebQuery(version='bayestar2017')
reddening = bayestar(V404, mode='median')
```

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-12-cb588282d760> in <module>()
>       1 bayestar = BayestarWebQuery(version='bayestar2017')
> ----> 2 reddening = bayestar(V404, mode='median')
> 
> /anaconda3/lib/python3.6/site-packages/dustmaps/map_base.py in _wrapper_func(self, coords, **kwargs)
>     108         if not isinstance(coords, coordinates.SkyCoord):
>     109             raise TypeError('`coords` must be an astropy.coordinates.SkyCoord object.')
> --> 110         return f(self, coords, **kwargs)
>     111     return _wrapper_func
>     112 
> 
> /anaconda3/lib/python3.6/site-packages/dustmaps/map_base.py in __call__(self, coords, **kwargs)
>     433         An alias for ``WebDustMap.query``.
>     434         """
> --> 435         return self.query(coords, **kwargs)
>     436 
>     437     @ensure_coord_type
> 
> /anaconda3/lib/python3.6/site-packages/dustmaps/map_base.py in _wrapper_func(self, coords, **kwargs)
>     108         if not isinstance(coords, coordinates.SkyCoord):
>     109             raise TypeError('`coords` must be an astropy.coordinates.SkyCoord object.')
> --> 110         return f(self, coords, **kwargs)
>     111     return _wrapper_func
>     112 
> 
> /anaconda3/lib/python3.6/site-packages/dustmaps/map_base.py in api_wrapper(self, *args, **kwargs)
>     267 
>     268             # Serialize the arguments
> --> 269             data = json.dumps(data, cls=encoder)
>     270 
>     271             # POST request to server
> 
> /anaconda3/lib/python3.6/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
>     236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
>     237         separators=separators, default=default, sort_keys=sort_keys,
> --> 238         **kw).encode(obj)
>     239 
>     240 
> 
> /anaconda3/lib/python3.6/json/encoder.py in encode(self, o)
>     197         # exceptions aren't as detailed.  The list call should be roughly
>     198         # equivalent to the PySequence_Fast that ''.join() would do.
> --> 199         chunks = self.iterencode(o, _one_shot=True)
>     200         if not isinstance(chunks, (list, tuple)):
>     201             chunks = list(chunks)
> 
> /anaconda3/lib/python3.6/json/encoder.py in iterencode(self, o, _one_shot)
>     255                 self.key_separator, self.item_separator, self.sort_keys,
>     256                 self.skipkeys, _one_shot)
> --> 257         return _iterencode(o, 0)
>     258 
>     259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,
> 
> /anaconda3/lib/python3.6/site-packages/dustmaps/json_serializers.py in default(self, o)
>     373                 else:
>     374                     return o
> --> 375             return json.JSONEncoder.default(self, o)
>     376 
>     377     return MultiJSONEncoder
> 
> /anaconda3/lib/python3.6/json/encoder.py in default(self, o)
>     178         """
>     179         raise TypeError("Object of type '%s' is not JSON serializable" %
> --> 180                         o.__class__.__name__)
>     181 
>     182     def encode(self, o):
> 
> TypeError: Object of type 'bytes' is not JSON serializable

**Comment by gregreen** [comment]
@eblur Could you verify that fe29531 fixes this issue? It seems to work for Python3 in my testing.
