### ISSUE TITLE
Peek & Graves 2010

### ISSUE THREAD

**Issue by gregreen** [gregreen/dustmaps#13]
Add in Peek & Graves correction to SFD. The data can be found at https://doi.org/10.7910/DVN/VBSI4A.

**Comment by gregreen** [comment]
I'm working on this now. @jegpeek, which default behavior do you think would be more useful?

1. ``PeekGraves2010Query.query(coords)`` returns SFD + PG2010 correction.
2. ``PeekGraves2010Query.query(coords)`` returns PG2010 correction.

**Comment by gregreen** [comment]
@jegpeek, can you check that this code works as you would expect?

I still have to add documentation for PG2010. When that's done, I think the code will be ready to merge into the master branch.

**Comment by jegpeek** [comment]
Looks like it's working great to me! Thank you so much!!

So here's the question: right now it returns what should be _subtracted_ from SFD to improve it (according to PG10) which is indeed what we report in Figure 6. Is that reasonable behavior? It should be documented either way.

**Comment by gregreen** [comment]
I think it's reasonable behavior, because `dustmaps` should match the map provided by PG10 exactly. Doing anything else is a recipe for confusion. I'll update the documentation to make this clear.

**Comment by gregreen** [comment]
v1.0.3 (8259281) includes PG10, including documentation.
