### ISSUE TITLE
Results (uncertainties of reddening) from Web query form different from API query?

### ISSUE THREAD

**Issue by Ompha** [gregreen/dustmaps#15]
Hi, 
When I use the web query form (at [http://argonaut.skymaps.info/query]), it gives the uncertainty of extinction \pm 0.02 for distances less than 1kpc(take equatorial coordinate (19.486306, 40.59179) for example, E(B-V) = 0.02 \pm 0.02 at 0.31 kpc).  
And when I use API to query and  specify 
`bayestar = BayestarWebQuery(version='bayestar2017')
reddening= bayestar(coords , mode = 'percentile', pct = [16,50,84.])`
It gives `E(B-V) = [0.012 , 0.017,0.019]`
So from that, it seems the uncertain for E(B-V) at that coordinate is -0.005/+0.002?

My question is: does the 16th, and 84th percentiles gives something equivalent to uncertainty of the E(B-V) from the web query form? If not, which argument do I call to obtain uncertainty for reddening at a certain coordinate using API? I tried to find it in the documentation the but maybe I missed it?
Thank you very much for your time. 
Best
Cicero

**Comment by gregreen** [comment]
@Ompha In [the web form](http://argonaut.skymaps.info/query), I add 0.02 mag in quadrature to the uncertainties. If you take the uncertainties given by the API and transform them as

    σ² → σ² + (0.02 mag)²,

you should get the same results as the web form gives.

**Comment by Ompha** [comment]
Thank you very much for the explanation!
