### ISSUE TITLE
UnicodeDecodeError during installation

### ISSUE THREAD

**Issue by JorisDeRidder** [gregreen/dustmaps#17]
During installation (both 'pip' or 'python setup.py'), I faced the error:
 
> Traceback (most recent call last):
>  File "setup.py", line 135, in <module>
>    long_description=readme(),
>  File "setup.py", line 128, in readme
>    return f.read()
> [...]
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 714: ordinal not in range(128)

The setup.py can't read the README.md file. Replacing in the latter file 'Doré' with 'Dore' solved the problem.

**Comment by JorisDeRidder** [comment]
Python 3.6.4, installed with Anaconda.

**Comment by gregreen** [comment]
@JorisDeRidder Does the code work if you change `open('README.md', 'r')` to `open('README.md', mode='r', encoding='utf-8')`?
