### ISSUE TITLE
Gradients

### ISSUE THREAD

**Issue by MilesCranmer** [gregreen/dustmaps#19]
Hi @gregreen, great project - it is very helpful.

I need to read more, but I was wondering if it is possible to compute the gradient of dust with respect to position with this package (using Bayestar 2017 map)? I could estimate it numerically but I was wondering if there is a more clever way using the actual model used.

Thanks,
Miles

**Comment by gregreen** [comment]
Do you mean the derivative of reddening along the line of sight, or really the gradient of reddening (or perhaps dust density)?

**Comment by MilesCranmer** [comment]
Sorry for the confusion.

You are correct. I am interested in the derivative of the dust density along the line of sight (I suppose this is the most useful direction to me). However, I would also be interested in the derivatives with respect to sky coordinates (so the full 3D gradient).

Maybe it makes sense to just compute this numerically but perhaps the internal model can be differentiated smoothly?

**Comment by gregreen** [comment]
No worries!

The internal model can indeed be differentiated along the line of sight. There's no feature in the code that does this, at the moment.

The most principled way to do so would be to modify [this line](https://github.com/gregreen/dustmaps/blob/82592815119fb828818bca6387c511757c2e5416/dustmaps/bayestar.py#L255) to include a boolean "derivative" keyword. This would take some reworking of the logic involved in selecting the correct distance bin. If you're interested in having this feature, I can try to add it in.

If you want to get the derivatives right away, however, I would recommend computing them numerically. Within the closest distance bin (< 63 pc), the d(reddening)/d(distance) is just the value of the first distance slice of the map, divided by 63 pc. Between any two distance slices of the map (I'll call them 0 and 1), the d(reddening)/d(distance) is just (reddening_1-reddening_0)/(distance_1-distance_0).

You can get the locations of the distance bins using the property `BayestarQuery.distances`.

**Comment by MilesCranmer** [comment]
Great, thanks for your help! I think I will do it numerically for now.
