### ISSUE TITLE
Holes in Bayestar

### ISSUE THREAD

**Issue by MilesCranmer** [gregreen/dustmaps#20]
Hi,

I was wondering if there are any descriptions of the holes in Bayestar?

After filtering out data above -30 dec, I was encountering Nans in my code and eventually narrowed it down to the map itself. There is one coordinate that was above -30 dec but was still seeing Nans from the Bayestar query. I looked further into this and indeed Bayestar has one tiny streak of data above -30 dec that is incomplete (the yellow):

![screen shot 2019-02-08 at 10 12 05 am](https://user-images.githubusercontent.com/7593028/52486940-74688980-2b8a-11e9-8de2-225ed9cfc850.png)

(y-axis is declination, x-axis is right ascension (ICRS), and the yellow shows queries which return NaNs)

I have also found another smaller hole higher up in declination. Therefore I was wondering if there are any descriptions of holes in Bayestar that I can use to filter my data?

Thanks!
Miles

**Comment by MilesCranmer** [comment]
(Bayestar 2017 by the way)

**Comment by MilesCranmer** [comment]
Here are some high-dec examples encountered in my data:

```
>>> [bayestar(SkyCoord(337.03868614*u.deg,  68.9854601*u.deg, 1*u.kpc, frame='icrs')),
    bayestar(SkyCoord(246.76878453*u.deg,  -24.71668303*u.deg, 1*u.kpc, frame='icrs'))]
[nan, nan]
```

**Comment by MilesCranmer** [comment]
If anybody wants a quick hack to step around this problem, I'll just leave this here:
this function moves your sampling position up in declination by 0.05 degrees until it is out of the hole:

```
def move_sample_bayestar(ra, dec, distance, frame='icrs', recursive_depth=0):
    if recursive_depth > 50:
        raise NotImplementedError("Star is too far from region")
    
    output = bayestar(SkyCoord(ra, dec, distance, frame=frame))
    bad_sample = np.isnan(output)
    
    if len(bad_sample) > 0:
        output[bad_sample] = move_sample_bayestar(
            ra[bad_sample],
            dec[bad_sample] + 0.05*u.deg,
            distance[bad_sample],
            recursive_depth=recursive_depth+1)
    
    return output
```

**Comment by gregreen** [comment]
The holes near dec = -30 deg are simply due to the raggedness of the edge of the dust map (which is determined by the edge of the PS1 3pi survey). The holes at higher latitudes are pixels in which there were not enough stars with good photometry to fit line-of-sight reddening. They should be fairly rare. They're intrinsic to the Bayestar2017 map, so `dustmaps` can't really do anything about them.

**Comment by MilesCranmer** [comment]
Great, thank you, and sorry for my late response. I have simply excluded those points from my analysis.
