### ISSUE TITLE
Signal-to-noise 

### ISSUE THREAD

**Issue by MilesCranmer** [gregreen/dustmaps#23]
Hi @gregreen, 

I was wondering if there was a way to get signal-to-noise for a particular dust measurement?

My current strategy is to use random_sample to get a standard deviation, and divide the mean dust by that value. I then multiply this by `flags['converged'] * flags['reliable_dist']` to return a signal-to-noise for the dust measurement.

What do you think?
Cheers,
Miles

**Comment by gregreen** [comment]
@MilesCranmer The best way to get the uncertainty in the Bayestar dust maps is to do something like this:

    q = BayestarQuery()
    E = q(coords, mode='percentile', pct=[16., 50., 84.])

where `coords` is an `astropy.coordinates.SkyCoord` object. That will return the 16th, 50th and 84th percentile of reddening for each coordinate. You can use the difference between the 84th and 16th percentiles to get 2σ.

See [the documentation](https://dustmaps.readthedocs.io/en/latest/modules.html#dustmaps.bayestar.BayestarQuery.query) for `BayestarQuery.query()`.

**Comment by MilesCranmer** [comment]
Thanks, this helps a lot.
