### ISSUE TITLE
Radius of regions?

### ISSUE THREAD

**Issue by theparmis** [gregreen/dustmaps#26]
Hi,
Thanks for providing such a great package!

When we use PlanckQuery or SFDQuery, as inputs we give RA and DEC to obtain E(B-V) values, but there is question.

What is size of my region? Is that circle or square? What is area of that region? Imagine situation for a single RA and DEC not an array.

When we compare values of Planck map and SFD98, Are they in same area? 

That would be great if we can assign radius around each position, but I didn't find any proper documentation...

Thanks Gregory.

**Comment by theparmis** [comment]
Any update?

**Comment by gregreen** [comment]
The estimates are point estimates, at the exact location you specify. There is no averaging over any region.

That being said, each dust map has its own resolution, smoothing, etc. The SFD map, for example, is based on IRAS data smoothed with a Gaussian kernel to 6', as well as a temperature map with a 1.1-degree resolution. By contrast, the Bayestar dust maps (Green et al. 2015,2017,2019) have a very different pixelization scheme. They're based on measurements of stars, grouped into pixels ranging in scale from about 3.4' to about 14'.

The `dustmaps` package, however, just returns whatever estimate the given map reports at the specified coordinates.
