### ISSUE TITLE
Getting an (Nx120) matrix rather than an (Nx1) matrix

### ISSUE THREAD

**Issue by DavidMoiseNataf** [gregreen/dustmaps#28]
The Jupyter notebook cellblock is:

bayestar = BayestarWebQuery(version='bayestar2019')
c = SkyCoord(ra=RAlist,dec=DEClist,\
             distance=Distances*u.pc, frame='icrs')
c2 = SkyCoord(c.galactic.l,c.galactic.b,\
             distance=Distances*u.pc, frame='galactic')
reddening = bayestar(c2,  mode='percentile', pct=50.)
print(type(RAlist),type(DEClist),type(Distances))
print(np.shape(RAlist),np.shape(DEClist),np.shape(Distances))
print(np.shape(c2),np.shape(reddening))
print(np.mean(reddening),np.median(reddening),np.std(reddening))

The output is
<class 'astropy.table.column.Column'> <class 'astropy.table.column.Column'> <class 'numpy.ndarray'>
(1805,) (1805,) (1805,)
(1805,) (1805,)
nan nan nan

Also, for information's sake:
print(RAlist[0:9],DEClist[0:9],Distances[0:9])
yields:
    ra        
       deg        
------------------
 85.71952670160155
 331.5950430106236
 353.9369156021425
  9.97346964628328
 93.41934818819222
210.71561378901362
 87.73003127400648
10.016275437083367
13.227971468286738         dec        
        deg        
-------------------
  3.565786366255105
-48.483665728252454
  32.16632093528816
  72.07734177175224
-35.718843946170665
 -2.375407984123281
 10.609960476038683
-13.884890712331707
-43.910909132674455 [333.30949824 333.27503203 333.21547772 333.20185198 333.16732067
 333.11270716 333.03118245 332.99673381 332.96857719]

**Comment by gregreen** [comment]
@DavidMoiseNataf Can you try running the following?

    print(c2.distance)
    print(c2.distance.kpc)

**Comment by DavidMoiseNataf** [comment]
[333.30949824 333.27503203 333.21547772 ...  77.23171768  62.83209247
  59.71985571] pc
[0.3333095  0.33327503 0.33321548 ... 0.07723172 0.06283209 0.05971986]

**Comment by gregreen** [comment]
That rules out my first guess, which is that somehow ``c2.distance`` does not include a ``kpc`` attribute.

I've upgraded my version of Astropy to 4.0, and tried reproducing the behavior you saw earlier:

    import numpy as np
    import astropy.units as u
    from astropy.coordinates import SkyCoord
    from dustmaps.bayestar import BayestarQuery
    
    l = np.random.uniform(0., 360., 10) * u.deg
    b = np.random.uniform(-90., 90., 10) * u.deg
    d = np.random.uniform(0., 5000., 10) * u.pc
    
    c = SkyCoord(l, b, distance=d, frame='galactic')
    
    q = BayestarQuery(max_samples=2)
    
    r = q.query(c, mode='percentile', pct=50.)
    
    print('r.shape = {}'.format(r.shape))

After the usual messages that Bayestar gives while loading, I get the following output:

    r.shape = (10,)

Can you try running my above code, and tell me if you get the same result?

I've also noticed that in your first comment, the shape of the reddening output appears to be `(1805,)`. Maybe the original problem had to do with `c2` somehow not actually containing distances.

**Comment by DavidMoiseNataf** [comment]
This is strange, if it's not installed how is the other thing running?

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-72-d0d3c9a7caba> in <module>
     10 c = SkyCoord(l, b, distance=d, frame='galactic')
     11 
---> 12 q = BayestarQuery(max_samples=2)
     13 
     14 r = q.query(c, mode='percentile', pct=50.)

~/anaconda/lib/python3.6/site-packages/dustmaps/bayestar.py in __init__(self, map_fname, max_samples, version)
    103         t_start = time()
    104 
--> 105         with h5py.File(map_fname, 'r') as f:
    106             # Load pixel information
    107             print('Loading pixel_info ...')

~/anaconda/lib/python3.6/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
    406                 fid = make_fid(name, mode, userblock_size,
    407                                fapl, fcpl=make_fcpl(track_order=track_order),
--> 408                                swmr=swmr)
    409 
    410             if isinstance(libver, tuple):

~/anaconda/lib/python3.6/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = '/Users/davidnataf/anaconda/lib/python3.6/site-packages/dustmaps/data/bayestar/bayestar2019.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by DavidMoiseNataf** [comment]
By the way, this is the output for c2

<SkyCoord (Galactic): (l, b, distance) in (deg, deg, pc)
    [(201.69559306, -13.49838618, 333.30949824),
     (347.79825416, -51.70665113, 333.27503203),
     (104.81315019, -28.02845235, 333.21547772), ...,
     (355.99479852, -36.44854636,  77.23171768),
     (275.24667868,  13.06897038,  62.83209247),
     (184.13045138,  -1.61380232,  59.71985571)]>

**Comment by gregreen** [comment]
The error is due to not having the full Bayestar2019 map sitting on your hard drive. You can change the line

    q = BayestarQuery(max_samples=2)

to the following:

    q = BayestarWebQuery()

That will make `dustmaps` ping `argonaut.skymaps.info`, rather than doing the query locally.

When I run with that change, I get the same result:

    r.shape = (10,)

**Comment by DavidMoiseNataf** [comment]
r.shape = (10,)

**Comment by DavidMoiseNataf** [comment]
Gaia2MASS_V2.fits
<https://drive.google.com/file/d/1esVogkGOKk9ncmWPbOYMAQr5qN-YZYxF/view?usp=drive_web>
This is the data I'm using, I'll send you the code in a minute.

*-------------*







*David M. NatafAssistant Research ScientistDepartment of Physics and
AstronomyThe Johns Hopkins University3400 N. Charles StreetBaltimore, MD
21218Phone: 443-410-1866*

**Comment by DavidMoiseNataf** [comment]
I just sent you the fits file I'm using, here's the code:

Gaia2MASS = Table.read('/Users/davidnataf/LMCSMC_RC/Gaia2MASS_v2.fits') ## required pi >= 3
use = np.where((name1 == name2) & (Gaia2MASS['Jmag']-Gaia2MASS['Kmag']>=0.60) \
               & (Gaia2MASS['Jmag']-Gaia2MASS['Kmag']<=0.70) &\
                (MKs>=-1.70) & (MKs<=-1.60)  )
Distances = 1000/np.asarray(Gaia2MASS['parallax'][use])
RAlist = np.asarray(Gaia2MASS['ra'][use])
DEClist = np.asarray(Gaia2MASS['dec'][use])
bayestar = BayestarWebQuery(version='bayestar2019')
c = SkyCoord(ra=RAlist*u.deg,dec=DEClist*u.deg,\
             distance=Distances*u.pc, frame='icrs')
c2 = SkyCoord(c.galactic.l,c.galactic.b,\
             distance=Distances*u.pc, frame='galactic')
reddening = bayestar(c2,  mode='percentile', pct=50.)
print(type(RAlist),type(DEClist),type(Distances))
print(np.shape(RAlist),np.shape(DEClist),np.shape(Distances))
print(np.shape(c2),np.shape(reddening))
print(np.mean(reddening),np.median(reddening),np.std(reddening))
