### ISSUE TITLE
Downloading IPHAS data 

### ISSUE THREAD

**Issue by andersdot** [gregreen/dustmaps#3]
I'm trying to download the IPHAS dust map using 

import dustmaps.iphas
dustmaps.iphas.fetch()

and at the end of the download I get the following error: 

Downloading http://www.iphas.org/data/extinction/A_samp_030.tar.gz
Repacking files...
Progress: .---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-37167cd28bb2> in <module>()
      1 import dustmaps.iphas
----> 2 dustmaps.iphas.fetch()

//anaconda/lib/python2.7/site-packages/dustmaps/iphas.pyc in fetch(clobber)
    379     # Convert from ASCII to HDF5 format
    380     print('Repacking files...')
--> 381     ascii2h5(dest_dir, os.path.join(dest_dir, 'iphas.h5'))
    382 
    383     # Cleanup

//anaconda/lib/python2.7/site-packages/dustmaps/iphas.pyc in ascii2h5(dirname, output_fname)
    306 
    307     tar_fname_list = glob(os.path.join(dirname, 'A_samp_*.tar.gz'))
--> 308     d = np.hstack([process_tarball(fn) for fn in tar_fname_list])
    309 
    310     print('+', end='')

//anaconda/lib/python2.7/site-packages/dustmaps/iphas.pyc in process_tarball(tarball_fname)
    267         sys.stdout.flush()
    268 
--> 269         with closing(tarfile.open(tarball_fname, mode='r:gz')) as f_tar:
    270             fnames = f_tar.getnames()
    271 

NameError: global name 'closing' is not defined

and my iphas directory looks like:

/Users/landerson/dustMaps/iphas
A_samp_030.tar.gz	A_samp_070.tar.gz	A_samp_110.tar.gz	A_samp_150.tar.gz	A_samp_190.tar.gz
A_samp_040.tar.gz	A_samp_080.tar.gz	A_samp_120.tar.gz	A_samp_160.tar.gz	A_samp_200.tar.gz
A_samp_050.tar.gz	A_samp_090.tar.gz	A_samp_130.tar.gz	A_samp_170.tar.gz	A_samp_210.tar.gz
A_samp_060.tar.gz	A_samp_100.tar.gz	A_samp_140.tar.gz	A_samp_180.tar.gz

**Comment by gregreen** [comment]
I've just pushed a fix to the `develop` branch: 0ca5ba3e18bdc7954d3dd8615c8e7faa05a3357f.

The issue was that `contextlib` was not being imported. If you download and install the `develop` branch, this issue should be resolved.
