### ISSUE TITLE
Allow override of default config location

### ISSUE THREAD

**Issue by SimonKrughoff** [gregreen/dustmaps#32]
I have put together a PR (#31) to allow for an environment variable to override the default location of the configuration overrides for `dustmaps`.  There is a bit more explanation in the PR itself.

**Comment by gregreen** [comment]
Thank you for this PR. It looks like useful functionality. I will give it a closer look.

**Comment by gregreen** [comment]
I made a few modifications/additions and merged the pull request into develop. I'll push a new version to pip later today. Thanks for this addition.

**Comment by SimonKrughoff** [comment]
Thanks for taking it!
