### ISSUE TITLE
1.0.7 release with most recent changes

### ISSUE THREAD

**Issue by SimonKrughoff** [gregreen/dustmaps#34]
@gregreen there was a little discussion of this on a PR, but I'm moving to an issue for better visibility.  I'm requesting a v1.0.7 release which will contain the most recent merged PR.  This change set is needed for me to make this package a requirement of our packages.  Let me know if there is anything I can do to help that along.

Thanks very much for maintaining this very useful package!

**Comment by gregreen** [comment]
@SimonKrughoff, I've created the 1.0.7 release and uploaded it to [GitHub](https://github.com/gregreen/dustmaps/releases/tag/v1.0.7) and [PyPi](https://pypi.org/project/dustmaps/1.0.7/). Let me know if you have trouble installing it for some reason. Thanks again for your contributions to `dustmaps`.

**Comment by SimonKrughoff** [comment]
Just to follow up on the conda-forge side of things: I see a new tag, so I think it "Just Works"™ when you do a release on github: https://anaconda.org/conda-forge/dustmaps
