### ISSUE TITLE
Planck 2018 GNILC mdust map

### ISSUE THREAD

**Issue by AstroMike** [gregreen/dustmaps#35]
This package looks excellent! Thanks.

I was wondering if it would be possible to include the 2018 Planck GNILC maps (it seems that the only Planck version is from 2013?) ... according to this paper https://ui.adsabs.harvard.edu/abs/2021MNRAS.tmp..577S/abstract it's the best option at low latitudes (Planck 2013 being poorer than SFD).

**Comment by gregreen** [comment]
Thanks for the suggestion. I think you mean the 2016 Planck GNILC maps: https://ui.adsabs.harvard.edu/abs/2016A%26A...596A.109P/abstract. I've started working on incorporating it.

**Comment by AstroMike** [comment]
Yes,  think I do mean 2016! Thanks!

**Comment by gregreen** [comment]
I've implemented the Planck GNILC reddening map in the develop branch. See b8df18161472eadb33bb4e543d194f3ed60de911.

I've looked at the results myself, and they appear fine to the eye, but it would be helpful if you could also try out the new map and let me know if things look reasonable. If I'm confident that the GNILC map is implemented correctly, then I'll merge it into the main branch.

**Comment by AstroMike** [comment]
I have plotted them and they look sensible to me (although I have only tried the defaults maps without errors).

GNILC vs Planck 2013

![EBV_GNILC_P13](https://user-images.githubusercontent.com/5515374/114763423-c429d900-9d30-11eb-9cc9-172b53cd12a4.png)

GNILC vs SFD (actually agrees better with SFD than it does with Planck 13 : note the different colorbar scale)

![EBV_GNILC_SFD](https://user-images.githubusercontent.com/5515374/114763441-c9872380-9d30-11eb-88e3-99747a321701.png)

**Comment by AstroMike** [comment]
Is the above sufficient? Do you want me to close this issue?

**Comment by gregreen** [comment]
The plots you made look reasonable. I'll close the issue and merge into the main branch.

**Comment by gregreen** [comment]
I've created release v1.0.8, which includes GNILC.
