### ISSUE TITLE
Astropy: deprecated properties

### ISSUE THREAD

**Issue by gregreen** [gregreen/dustmaps#37]
When serializing an astropy `SkyCoord`, recent versions of astropy warn that `SkyCoord.representation` is deprecated:

    WARNING: AstropyDeprecationWarning: The `representation` keyword/property name is deprecated
    in favor of `representation_type` [astropy.coordinates.baseframe]

This is due to the line

    representation = o.representation.get_name()

in `serialize_skycoord`, in [json_serializers.py](https://github.com/gregreen/dustmaps/blob/6f8601dda5b238d0946c3b8f0fed717fee151f35/dustmaps/json_serializers.py#L269).

How to deal with this? Check for `representation_type` first, and then fall back to `representation` if needed? The JSON decoder would probably have to be updated as well.

**Comment by hombit** [comment]
Hey, it looks like this deprecation became a runtime error since astropy 5.0
