### ISSUE TITLE
Removing progressbar2 as dependency

### ISSUE THREAD

**Issue by Edenhofer** [gregreen/dustmaps#44]
I thought I would bring this up since you mentioned you like cutting down on the number of dependencies; What do you think about replacing the current dependency on progressbar2 with a simple DIY progressbar. I have a very crude implementation of a tqdm-like default progress bar lying around that is only a couple hundred lines of code. One could verbatim copy this implementation to dustmaps and adjust it to be a progressbar for file downloads.

**Comment by gregreen** [comment]
There are a few standard progressbar implementations (`progressbar2`, `tqdm`, probably others), so I'd rather not reinvent the wheel here.

**Comment by Edenhofer** [comment]
I think tqdm is far more popular. Currently, dustmaps is the only Python package that I have installed that requires progressbar2. I am always happy to drop a dependency for ~100 lines of self-written code (the DIY one is 80 LOC).

I understand your point though that you don't want a certainly less well tested DIY progress bar if you are already using an established one. I will not be working on this then.
