### ISSUE TITLE
Add Lenz, Hensley, Doré map?

### ISSUE THREAD

**Issue by DanielLenz** [gregreen/dustmaps#5]
Hi Greg, thanks for making this package available! Would you mind including the E(B-V) map that I published a few months ago with Brandon Hensley and Olivier Doré ([paper](http://adsabs.harvard.edu/abs/2017ApJ...846...38L), [data](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/AFJNWJ))?
I could also take a look at the code and make a PR.
Thanks,
Daniel

**Comment by gregreen** [comment]
Hi Daniel, I'll add it in. Since it's a HEALPix map and is hosted on the Harvard Dataverse, it should be easy to add in.

**Comment by gregreen** [comment]
@DanielLenz , your map is now included in the current master branch: https://github.com/gregreen/dustmaps/blob/0ba4858d2a02018481c982919f3a796ece74955e/dustmaps/lenz2017.py

Please take a look at the documentation [here](http://dustmaps.readthedocs.io/en/latest/maps.html#lenz-hensley-dore-2017) and [here](http://dustmaps.readthedocs.io/en/latest/modules.html#dustmaps.lenz2017.Lenz2017Query).

There's a plotting example [here](https://github.com/gregreen/dustmaps/blob/master/dustmaps/examples/plot_lenz2017.py).

Please let me know if anything looks wrong or doesn't work.

**Comment by DanielLenz** [comment]
Hi @gregreen , thanks for including the map! Everything looks good and works for me.
