### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by sonithls** [gregreen/dustmaps#57]
Hi, I am getting a similar error #42  while using dustmap. Thanks for the solution using "BayestarQuery"

Response received from server:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by gregreen** [comment]
This was a problem with the server, which I have now fixed.
