### ISSUE TITLE
planck map implementation  broken

### ISSUE THREAD

**Issue by harenk** [gregreen/dustmaps#6]
both python 2.7x and 3.x do not work. python 3.x additionally need brush up of string handling. 
[ planck]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import print_function
>>> from astropy.coordinates import SkyCoord
>>> from dustmaps.planck import PlanckQuery
>>>
>>> coords = SkyCoord('12h30m25.3s', '15d15m58.1s', frame='icrs')
>>> planck = PlanckQuery()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/dustmaps/planck.py", line 94, in __init__
    field=field)
  File "/usr/lib/python2.7/site-packages/dustmaps/healpix_map.py", line 108, in __init__
    if close_file:
UnboundLocalError: local variable 'close_file' referenced before assignment
>>> ebv = planck(coords)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'planck' is not defined

**Comment by gregreen** [comment]
Thanks for the bug report. I think the commit mentioned above fixes the problem. I'll upload it to PyPi with a couple of other updates soon.

**Comment by gregreen** [comment]
I haven't tested `dustmaps` with Python 3.x. If there are issues with it, feel free to file a bug report. If the package just doesn't work at all, let me know.
